import Head from "next/head";
import Image from "next/image";
import React from "react";

export default function Home() {
	return (
		<>
			<Head>
				<title>Sustainable Progress and Equality Collective</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen items-center justify-content px-10 pt-10 md:w-full 2xl:w-1/2 m-auto">
				<div className="w-full">
					<header className="lg:flex lg:items-center pb-10">
						<Image
							className="m-auto lg:m-0 lg:inline text-left"
							src="/spec-logo.svg"
							alt="spec-logo"
							width={120}
							height={120}
							priority
						/>
						<h1 className="block text-center lg:text-left text-4xl xl:text-3xl font-medium font-montserrat">
							Sustainable Progress and Equality Collective
						</h1>
					</header>

					<section className="mb-4">
						<h2 className="mb-4 font-dmserif text-4xl font-normal text-spec-black">
							We are a radically transparent learning organization advancing{" "}
							<span className="text-spec-lightRed">sustainability</span> and{" "}
							<span className="text-spec-lightRed">social equity</span>{" "}
							through...
						</h2>
					</section>

					<section className="py-4 font-dmserif">
						<h3 className="mb-2 font-dmserif text-3xl font-normal text-spec-turquiose">
							Community-engaged research
						</h3>
						<p className="font-montserrat text-2xl">
							We engage communities through <b>action-oriented research</b> to
							develop <b>community-driven solutions</b> to local and global
							problems.
						</p>
					</section>

					<section className="py-4 font-dmserif">
						<h3 className="mb-2 font-dmserif text-3xl font-normal text-spec-turquiose">
							Professional service learning
						</h3>
						<p className="font-montserrat text-2xl">
							We provide <b>paid work experiences</b> that help people learn
							through service, contributing to{" "}
							<b>real-world social impact projects</b>.
						</p>
					</section>

					<section className="mb-10 py-4">
						<h3 className="mb-2 font-dmserif text-3xl font-normal text-spec-turquiose">
							Open collaborative innovation
						</h3>
						<p className="font-montserrat text-2xl">
							We are committed to <b>open source and open access</b> and
							operating transparently to foster{" "}
							<b>inclusion, accessibility, and innovation</b>.
						</p>
					</section>

					<section className="bg-spec-yellow py-10 px-4">
						<div className="grid grid-cols-1 items-center gap-0 lg:gap-6 xl:grid-cols-2">
							<div className="col-span-1 text-center font-montserrat text-2xl xl:text-center">
								Want to get involved?
							</div>

							<div className="gap-30 col-span-1 grid grid-cols-1 lg:grid-cols-2">
								<div className="py-2 text-center">
									<a
										href="https://docs.specollective.org"
										target="_blank"
										rel="noreferrer"
										className="mr-1 p-2 font-montserrat text-xl font-medium underline">
										DOCUMENTATION
									</a>
								</div>

								<div className="text-center">
									<a
										href="https://opencollective.com/spec"
										className="block bg-spec-turquiose text-center p-2 text-2xl font-medium text-white rounded-br-lg rounded-tl-lg font-montserrat w-3/4 m-auto">
										DONATE
									</a>
								</div>
							</div>
						</div>
					</section>
				</div>
			</main>
		</>
	);
}
